apiVersion: v1
kind: PersistentVolume
metadata:
  name: odoo-pv
  labels:
    app: odoo
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: odoo-local
  local:
    path: /node1-data/odoo
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node1-132
