apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresodoo-pv
  labels:
    app: postgres
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: postgres-local
  local:
    path: /node1-data/postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node1-132
