apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.odoo.name }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.odoo.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.odoo.size }}
  storageClassName: {{ .Values.persistence.odoo.storageClass }}
