apiVersion: v1
kind: Service
metadata:
  name: odoo
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: odoo
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8069
